name: sram

outputs:
        - sram.sp
        - sram.v
        - sram.lib
        - sram.lef
        - sram_TT_3p3V_25C.lib
        - sram_TT_3p3V_25C.db
        - sram.gds

commands:
        - python3 $OPENRAM_HOME/openram.py sramconfig.py
        - ./convert_lib_to_db.sh outputs
